### ISSUE TITLE
fatal: unable to exec /LoginScript.sh: Permission denied

### ISSUE THREAD

**Issue by LexJackson** [RFBomb/nordvpn#1]
When trying to start the container I get the following logs and the container terminates. I'm running this on an Asus Tinkerboard running Armbian. Not sure where to begin as this error appears to be coming from inside the container. Thanks in advance! 

_Docker Log------------------------------_
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
**exec: fatal: unable to exec bash: Exec format error
s6-supervise (child): fatal: unable to exec run: Exec format error
s6-supervise nordvpn: warning: unable to spawn ./run - waiting 10 seconds
[services.d] done.
ifelse: fatal: unable to exec /LoginScript.sh: Permission denied
[cmd] /LoginScript.sh exited 126**
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
_End Docker Log -----------------------------_

_docker-compose.yml ----------------------------_

version: '2'
services:
#--------------   VPN  ---------------------------
 vpn:
  image: rfbomb/nordvpn
  container_name: NordVPN
  stdin_open: true
  tty: true
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  networks:
      - TS_Bridge
  #Expose all ports required by other services behind the VPN
  expose:
     - 80
     - 9090
     - 8112
  environment:
     - PUID=501
     - PGID=998
     - USER=cleverusername@somemail.com
     - PASS='AwesomePassword'
     - HostSubnet=192.168.15.0/24
     - DockerSubnet=172.16.0.0/24
     - AUTOCONNECT=on
     - KILLSWITCH=on
     - CYBERSEC=off
     - OBFUSCATE=off
     - SERVER=P2P
  #restart: unless-stopped

#--------------   Services Behind VPN  ---------------------------
 deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: service:vpn
    environment:
      - PUID=501
      - PGID=998
      - TZ=timezone
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /mnt/docker/deluge/config:/config
      - /mnt/docker/downloads:/downloads
    restart: unless-stopped

#--------------   Reverse Proxy  ---------------------------
 proxy:
    image: linuxserver/nginx
    container_name: nginx
    environment:
    - PUID=501
    - PGID=998
    stdin_open: true
    tty: true
    networks:
      - TS_Bridge
   #Map all ports that are exposed in the VPN service
    ports:
     - "80:80"
     - "9090:9090"
     - "8112:8112"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nginx/config:/config/
   #restart: unless-stopped

#--------------  Network Definition (if desired) ---------------------------
networks:
  TS_Bridge:
    driver: bridge
    ipam:
     driver: default
     config:
      - subnet: 172.16.0.0/24

**Comment by RFBomb** [comment]
I have been busy, but steadily working on the container. 
I am updating it now. Sorry about the delay.

(Hopefully an update to nordvpn app doesn't break it again)

**Comment by LexJackson** [comment]
Thanks!

**Comment by LexJackson** [comment]
@RFBomb Have you done much testing of the new NordLynx protocol? Stable? Cheers

**Comment by RFBomb** [comment]
I have done absolutely zero testing within the container. I used it in a
native system once, which worked fine, but then I updated my Pi to a
different OS and never bothered changing it back to nordlynx.

All I did was expose the option within the login script, since it is
available, rather than requiring you to attach to the container.

If you run into any other issues, let me know.

**Comment by LexJackson** [comment]
@RFBomb Thanks again!
